#!/usr/bin/env python3
"""Render the dex2jar-skills feature tree as a Unicode tree.

Single source of truth for the "feature tree" shown in README.md and
README.zh-CN.md. Unlike the Mermaid mindmap (which only renders on GitHub),
this produces a plain-text box-drawing tree that displays in *any* Markdown
viewer, terminal, or plain text — and stays in sync because both READMEs are
generated from the TREE below.

Usage:
    python3 tools/feature_tree.py                 # print English tree
    python3 tools/feature_tree.py --lang zh       # print Chinese tree
    python3 tools/feature_tree.py --write         # inject both into the READMEs
    python3 tools/feature_tree.py --check         # verify READMEs are in sync (CI)

The injected region is delimited in each README by:
    <!-- FEATURE-TREE:START (auto-generated by tools/feature_tree.py) -->
    <!-- FEATURE-TREE:END -->
"""
from __future__ import annotations

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Each node is (en_label, zh_label, [children]). Leaves have an empty child list.
# This mirrors the Mermaid mindmap so the two stay conceptually identical.
TREE = (
    "dex2jar-skills  ·  AI-native Android RE",
    "dex2jar-skills  ·  AI 原生 Android 逆向",
    [
        ("AI-native access", "AI 原生接入", [
            ("Claude Code plugin", "Claude Code 插件", [
                ("3 Skills", "3 个 Skills", []),
                ("29 slash commands", "29 条斜杠命令", []),
                ("reverse-engineer agent", "reverse-engineer 智能体", []),
            ]),
            ("MCP server", "MCP 服务器", [
                ("Claude Desktop", "Claude Desktop", []),
                ("any MCP client", "任意 MCP 客户端", []),
            ]),
            ("Structured-JSON CLI", "结构化 JSON 命令行", []),
        ]),
        ("Skills", "Skills 技能", [
            ("dex2jar — workbench", "dex2jar — 主工作台", []),
            ("apk-triage — fast first-pass", "apk-triage — 快速首过", []),
            ("sensitive-api-audit", "sensitive-api-audit — 敏感 API 审计", []),
        ]),
        ("Convert", "转换", [
            ("DEX <-> JAR", "DEX <-> JAR 互转", []),
            ("smali assemble / disassemble", "smali 汇编 / 反汇编", []),
            ("jasmin", "jasmin", []),
        ]),
        ("Analyze  (new in this fork)", "分析  (本 fork 新增)", [
            ("manifest & permissions", "清单与权限", []),
            ("signing certificate", "签名证书", []),
            ("strings", "字符串", []),
            ("call graph", "调用图", []),
            ("cross-references", "交叉引用", []),
            ("class dependencies", "类依赖", []),
            ("native .so / JNI", "native .so / JNI", []),
        ]),
        ("Rewrite / edit", "改写 / 编辑", [
            ("dex & jar weaver", "dex 与 jar 织入", []),
            ("access flags", "访问标志", []),
            ("class version", "class 版本", []),
            ("string decrypt / deobf", "字符串解密 / 反混淆", []),
        ]),
        ("Forensics", "取证", [
            ("ODEX stub generation", "ODEX 桩生成", []),
            ("coredump extraction", "coredump 提取", []),
        ]),
        ("Inherited from dex2jar", "继承自 dex2jar", [
            ("dex read / write", "dex 读 / 写", []),
            ("DEX <-> JAR conversion", "DEX <-> JAR 转换", []),
            ("APK signing", "APK 签名", []),
        ]),
    ],
)

# Box-drawing connectors.
TEE, ELBOW, PIPE, BLANK = "├── ", "└── ", "│   ", "    "

START = "<!-- FEATURE-TREE:START (auto-generated by tools/feature_tree.py) -->"
END = "<!-- FEATURE-TREE:END -->"


def _label(node, lang: str) -> str:
    en, zh, _children = node
    return zh if lang == "zh" else en


def _children(node):
    return node[2]


def render(node, lang: str = "en") -> str:
    """Return the tree rooted at ``node`` as a Unicode box-drawing string."""
    lines = [_label(node, lang)]

    def walk(children, prefix: str) -> None:
        last = len(children) - 1
        for i, child in enumerate(children):
            connector = ELBOW if i == last else TEE
            lines.append(prefix + connector + _label(child, lang))
            kids = _children(child)
            if kids:
                walk(kids, prefix + (BLANK if i == last else PIPE))

    walk(_children(node), "")
    return "\n".join(lines)


def _block(lang: str) -> str:
    """The full Markdown region (markers + fenced tree) for one language."""
    tree = render(TREE, lang)
    return f"{START}\n```text\n{tree}\n```\n{END}"


def _readmes():
    return {
        "en": os.path.join(ROOT, "README.md"),
        "zh": os.path.join(ROOT, "README.zh-CN.md"),
    }


def _inject(text: str, block: str) -> str:
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)
    if not pattern.search(text):
        raise SystemExit(
            "FEATURE-TREE markers not found — add the START/END comment pair first"
        )
    return pattern.sub(lambda _m: block, text)


def cmd_write() -> int:
    for lang, path in _readmes().items():
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        new = _inject(text, _block(lang))
        if new != text:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new)
            print(f"  updated {os.path.relpath(path, ROOT)}")
        else:
            print(f"  unchanged {os.path.relpath(path, ROOT)}")
    return 0


def cmd_check() -> int:
    rc = 0
    for lang, path in _readmes().items():
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        if _block(lang) not in text:
            print(f"  ❌ {os.path.relpath(path, ROOT)} feature tree is stale "
                  f"— run: python3 tools/feature_tree.py --write")
            rc = 1
        else:
            print(f"  ✅ {os.path.relpath(path, ROOT)} feature tree in sync")
    return rc


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Render the README feature tree.")
    ap.add_argument("--lang", choices=("en", "zh"), default="en",
                    help="language for plain stdout render (default: en)")
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--write", action="store_true",
                   help="inject the tree into README.md and README.zh-CN.md")
    g.add_argument("--check", action="store_true",
                   help="verify both READMEs are in sync (exit 1 if stale)")
    args = ap.parse_args(argv)

    if args.write:
        return cmd_write()
    if args.check:
        return cmd_check()
    print(render(TREE, args.lang))
    return 0


if __name__ == "__main__":
    sys.exit(main())
